= Getting started with terminal - Try replacing the websites with CLI

:date: 2019-01-10
:category: Command-Line
:tags: Command-Line, Productivity

== Intro:

In my opinion, using terminal makes you more productive and lets you get your mundane tasks done quickly. For ex, I spend no more than few seconds for the tasks like,

 - Encoding/Decoding a string to and from base64.
 - Formatting/Validating a JSON.
 - Formatting/Validating an XML.
 - Searching files containing a particular string.
 - Find and replace a particular pattern.
 - And similar tasks that I do regularly.

But it was a bit difficult for me to convey these things to the people around me and pass on the comfort that I have so that they will also get more productive on similar tasks.

This is an effor to try to convience someone to start using CLI.

== Step-by-step:
Typically, the general alternatives for the tasks mentioned above are some websites that offer encoding, decoding, formatting, and validation.  The steps to achieve what they intended to do is,

 - Copy the text that they need to encode/decode/validate/format.
 - Paste it to the site that performs expected action.
 - Click on encode/decode/validate/format.
 - Copy the output.
 - Paste it back to the intended place.

== Example:
I believe these are fair enough use-cases that let you start with command-line. I am trying to compare the step-by-step breakdown of CLI and non-CLI way of achieving a base64 encoding.

### Without using CLI,

- Copy the string that needs to be encoded.
- Open some website like www.base64encode.org and paste your string there.
- Click on encode.
- Copy the output text.
- Paste it in your intended location.

### While doing the same thing with CLI,

 - Copy the string that needs to be encoded.
 - In terminal execute the command `pbpaste|base64|pbcopy`.
 - Paste the base64 encoded string to the intended location.

> Note: `pbpaste` pastes the content from the clipboard, `pbcopy` copies the content to the clipboard.

== Benchmarking:

As verified, I took `28.62s` in the way of not using CLI and took `17.50s` when I executed in CLI.

To be fair, I assumed that I already have knowledge of http://www.base64.org[the site] and the knowledge of the commands and typed in those by hand.

The time taken when you using non-cli is nearly 63% more than the time it was taken in CLI. Further, you can save more time if you have the CLI version defined as an alias.

== Summary:

- Apart from the time that you save, CLI's are more native to your system that provides you more power which is not available otherwise. For ex, you can format the content of a json file and save it back using a single command, `cat "fileName" | jq . > "fileName"`. In a non-cli way you will be required to take care of file operations(reading/saving the file) yourself manually.
- You will also be able to combine multiple commands to achieve something new, that might not be possible when you are using separate services for each use cases.I'll try prove more on that in the upcoming articles.

In general I strongly believe that commands lets you do more without spending much time in fiddling on different services.