= Noise, Signal, Small, Huge, and More

:date: 2023-08-08
:category: Thoughts
:tags: Team, Actions, Introspection

Almost all of us want to make our mark in the world. And there are immortals who have a higher purpose more than just making a mark.

The latter is beyond my comprehension for the most part, but I'm an observer of actions of the former types now and then. This is about a thought on how people try to make their mark in an environment. In a fair environment, the value a person brings often correlates with the type of mark they aim to make. This write-up might be _Aha!_ read for a few or might be an introspection for others. Nevertheless, the purpose is to realize and grow.

Though the pattern can be expanded to broader context, I limit the content to workplaces. Based on how people are _”trying”_ to make a difference in the workplace, it could fall into one of these categories. It’s not necessary that a person always falls under the same category. It changes from time to time based on the decision that they make at the moment.

## Noise:

Making your mark by making some noise. Mostly BS, name calling, talking about things that you know nothing about more than just names, uttering jargons or acronyms that you can’t even answer the level-1 questions about.

Typically when doing this, the person is very less self-aware and tries this tactic to make a mark. The self-delusion is so high here(self-delusion is not exclusive here).

Signs that you’re in this are,
- Typically there will be no materialization.
- People rarely reach out to you for help unless you’re in power.

The effort of making a mark this way has almost no effect or has negative effect.

## Signal:

Might not be BS. But typically about virtue signaling on how good a person you are or how great your intentions are. These are words without any actions.

For example,
Whenever you say how much you love to do something but you couldn’t get a chance to do that something.
Whenever you say you couldn’t sleep when your team is working hard. Sometimes this could genuinely be true, sometimes you’re probably just signaling rather than actually doing anything useful.
And the peak of it, signaling modesty and openness by admitting that you just say more than you do.
You’re mostly lying to others, or worse to yourself.

Similar to noise, this might not also have any tangible result, but It might give a good feeling for you and people around you in the short-term. But in the longer run, remember, actions speak louder than words.

## Small:

Could be actions that you can do at the moment of need. Won’t take deeper thought to get it done and often inconsequential. And people may or may not find it very valuable.

I refrain from giving examples here, as sometimes it’s hard to define and people might argue how important the specific action is.

But it’s good to define it for yourself by asking the questions like,
Is it a consequential action?
Am I doing it because it is needed?

Sometimes the actions of small dents need to be done, because no place exists without chores. But the problem is ensuring that not filling up yourself with inconsequential actions and giving an excuse for not taking up consequential ones.

## Huge:

Action that is often thought through, long-termed. Probably need a consistent/meticulous/thought-through effort from people. These acts are highly consequential.

For example, making a decision of where you/your team/ your firm should be in a few months and consistently working towards it.

Though such actions are important and consequential, it’s important not to think so-high of one-self while involved in this. One great lesson from https://www.amazon.in/Skin-Game-Hidden-Asymmetries-Daily/dp/0141982659[The Skin in the Game], esp for people with consequential actions in hand is, owning the complete responsibility(not just in words) of the consequence even when you might not have obligation to do so.

## And More:

Apart from the aforementioned types, there are few people for who are beyond all these means of actions and they actually don't "try" to make a mark. And they are driven by fun for doing it or driven by a great purpose, etc. Usually, such people will end-up making huge dent, even though that’s not the goal for their action.

## Conclusion:

It's easy to define and hierarchy among people based on which of these categories their actions fall under. But that's not the purpose of this. Based what you want in life, or what your situations wants out of you, you can choose any of these actions at a given time. The purpose of this essay is just to make one conscious of their action and minimize delusion.

In other words, the goal is to encourage self-awareness and introspection about one's actions, rather than judgment or classification. Hope you find it solves the intended goal!
