= Reality might not be ideal, but thoughts can be

:date: 2018-12-11
:category: Introspection
:tags: Opinions, Thoughts

There are realities which when we discuss as a single statement holds true. For example, when we say _“No harm in just doing it once”_.


Logically speaking, _“Yes! Doing it once might not be harm.”_ But the problem in such case is not in doing it that on that particular time per se, but the thought that says _“No harm in just doing it once”_.
 
To generalize, it is true that the reality is not ideal, but when we fix our thought that reality is not ideal,
 
 - We are letting the things to be in a negative-spiral and will act only when things get worst, or we realize it by other means.
 - We accept the status quo and let the mediocrity continues.


Hence, though the reality might not be ideal, it’s good to have our thoughts ideal, thus opening up the space for improvement.

##### Note:

- This article is just my opinion on a step towards becoming ideal and not _"the solution"_.

- This article doesn’t insist the reader be ideal. If you wish to become ideal, reflecting your thoughts/statements in this perspective might help.