= Easy vs Right choice

:date: 2019-04-22
:category: Introspection
:tags: Introspection

The statement `easy vs right` applies to a wide variety of topic. I am limiting myself to discuss it with the context of choices that you have when your beliefs are challenged.

== Context:

Almost all of us are inclined/biased towards one stand or the other in preferences, starting from personal choices, way of life, religion, politics and so on.

Whenever confronted with 'facts/ideas/hypothesis' (`challenges`) that doesn’t agree with our intuitions, we try hard to ignore/make it invalid/false.

To an extent ^[1]^ this effort is ok, or else you will be detained by a lot of things, without exploring what you believe in. This post is about making a choice when you are in such a confrontation. This is no way a solution to the problem, but more of an opinion that I _feel_ is good to follow, based on knowledge and beliefs that I have.

== Easy choice:

When confronted with `challenges` that don't agree with our beliefs, we tend to ignore it or try to prove it wrong or worst mudslinging.

_'Easy choice'_ happens so commonly, especially when you are surrounded by people with the same belief as yours.

A good thing about this is you don't waste your time analyzing things that are not worthy. And a bad thing is you might not spend your time on things that might be worth spending time. At worst cases, it gets more egoistic and become more counter-productive.

== Right choice:

When you think you don't get much out of getting the challenge right or if it is costly (in terms of time, energy, money or mental-leap ^[2]^) to get it right, it's fine to let it go.

If not, the right thing would be to give the `benefit of the doubt` and doing a rational analysis to the best of your knowledge.

When you chose not to ignore, a bad thing is you are possibly dissipating your time and energy on things that's not much of your area of interest. A good thing is, you, along with others evolve into a better community. 

== Inspiration:

In a way, this thought is inspired by the movie “Vikram Vedha”. The hero “Vikram”, a talented, honest cop, who is swindled by his team to hunt down a gangster group and its leader “Vedha”. For _Vikram_, he is in the mission of hunting down a gangster. But for the rest of the team, they are doing it because they have been bribed by another group of a gangster. When confronted with questions from _Vedha_, an easy choice for _Vikram_ would have been to just shoot down _Vedha_, because he was just a gangster and no one would question him. But, when _Vikram_ sees a point in it, he chooses an uncomfortable path of knowing the truth.


[`1`] - Up to what extent is a big question that I don’t have an answer to yet.

[`2`] - Shifting your mental perspective, so that it requires changes in other parts of your life.